services:
  simple-app:
    image: spidero/simple-app
    container_name: simple-app
    expose:
      - "8000"

  simple-api:
    image: spidero/simple-api
    container_name: simple-api
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - simple-app
      - simple-api